#!/usr/bin/env bash
# refresh-hadiths.sh — pull authentic hadiths and cache one-line-friendly ones
# to hadiths.txt. The status line only ever reads that cache; it never hits the
# network. Run this whenever you want to refresh the pool (e.g. via cron/launchd).
#
# Source: https://github.com/fawazahmed0/hadith-api  (free, no API key)
# We pull only Sahih al-Bukhari and Sahih Muslim — the two Sahihayn — whose
# contents are authentic (sahih) by scholarly consensus, so every hadith pulled
# here qualifies as "confirmed". Each line keeps its collection + number so it's
# verifiable.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
OUT="$SCRIPT_DIR/hadiths.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

BASE="https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions"

# edition slug -> short attribution label
fetch() {
  local slug="$1" label="$2"
  echo "Fetching $slug ..." >&2
  curl -fsSL --max-time 90 "$BASE/$slug.json" -o "$TMP/$slug.json"
  printf '%s\t%s\n' "$slug" "$label" >> "$TMP/manifest"
}

fetch eng-bukhari "Bukhari"
fetch eng-muslim  "Muslim"

# Extract, clean, length-filter, de-dupe — write hadiths.txt.
MINLEN=40 MAXLEN=140 python3 - "$TMP" "$OUT" <<'PY'
import json, os, re, sys, glob
tmp, out = sys.argv[1], sys.argv[2]
minlen, maxlen = int(os.environ["MINLEN"]), int(os.environ["MAXLEN"])

labels = {}
with open(os.path.join(tmp, "manifest")) as f:
    for line in f:
        slug, label = line.rstrip("\n").split("\t")
        labels[slug] = label

lines, seen = [], set()
for path in sorted(glob.glob(os.path.join(tmp, "*.json"))):
    slug = os.path.splitext(os.path.basename(path))[0]
    label = labels.get(slug, slug)
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    for h in data.get("hadiths", []):
        text = re.sub(r"\s+", " ", (h.get("text") or "")).strip()
        if not (minlen <= len(text) <= maxlen):
            continue
        key = text.lower()
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"{text}  — {label} {h.get('hadithnumber')}")

with open(out, "w", encoding="utf-8") as f:
    f.write("# Authentic hadiths (Sahih al-Bukhari & Sahih Muslim) via fawazahmed0/hadith-api.\n")
    f.write("# Auto-generated by refresh-hadiths.sh — edits here are overwritten on refresh.\n")
    for ln in lines:
        f.write(ln + "\n")

print(f"Wrote {len(lines)} hadiths to {out}", file=sys.stderr)
PY
